name: PR Workflow

on:
  pull_request:
    branches: [development, release-*]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

permissions:
  contents: read
  security-events: write

jobs:
  run_tests:
    uses: tataranovich/ai-dial-ci/.github/workflows/python_docker_pr.yml@main
    with:
      python-version: "3.13"
      python-package-manager: "uv"
      uv-version: "0.11.28"
    secrets: inherit
